[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
match_solana_contract = "Gde2V9pUafhQSDMYNMhtGTjTDDWBvD9DZH251Hq26wgL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dave/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
